// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmoftyLPmu1CAAqk2fX-NLmJkjzoid6NU',
    appId: '1:223139901314:web:f345bde2d1018d128fa99b',
    messagingSenderId: '223139901314',
    projectId: 'celestial-cafe-pos-2026',
    authDomain: 'celestial-cafe-pos-2026.firebaseapp.com',
    storageBucket: 'celestial-cafe-pos-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG5fCwWsXZNcwz1dym8xXTBlLhdGarTOQ',
    appId: '1:223139901314:android:c25638178246ab248fa99b',
    messagingSenderId: '223139901314',
    projectId: 'celestial-cafe-pos-2026',
    storageBucket: 'celestial-cafe-pos-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW71vCYq2--QwUOgfSUvLn8auaAl6IVG8',
    appId: '1:223139901314:ios:b5309e0462cbdbf88fa99b',
    messagingSenderId: '223139901314',
    projectId: 'celestial-cafe-pos-2026',
    storageBucket: 'celestial-cafe-pos-2026.firebasestorage.app',
    iosBundleId: 'com.celestialcafe.celestialPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW71vCYq2--QwUOgfSUvLn8auaAl6IVG8',
    appId: '1:223139901314:ios:b5309e0462cbdbf88fa99b',
    messagingSenderId: '223139901314',
    projectId: 'celestial-cafe-pos-2026',
    storageBucket: 'celestial-cafe-pos-2026.firebasestorage.app',
    iosBundleId: 'com.celestialcafe.celestialPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmoftyLPmu1CAAqk2fX-NLmJkjzoid6NU',
    appId: '1:223139901314:web:35fe01d2adafba238fa99b',
    messagingSenderId: '223139901314',
    projectId: 'celestial-cafe-pos-2026',
    authDomain: 'celestial-cafe-pos-2026.firebaseapp.com',
    storageBucket: 'celestial-cafe-pos-2026.firebasestorage.app',
  );
}
